#!/bin/bash
echo "Compiling $1..."
if [ -z "$1" ]; then
	echo "Supply a god-damn file!"
else
	gcc -o a.out $1 &> /dev/null
	# if [ $(gcc $1 -o a.out &> /dev/null) ]; then
	if [[ $? -eq 0 ]]; then
		echo "Compilation success! Egguting..."
		./a.out
	else
		echo "Compilation failure!"
	fi
fi