#!/bin/bash

echo Enter number of fibonacci you want
read n
a=0
b=1
echo first $n fibonacci numbers are
echo $a 
echo $b
n=`expr $n - 2`
while [ $n -gt 0 ]
do
    c=`expr $a + $b`
    echo $c
    a=$b
    b=$temp
    n=`expr $n - 1`
done
