#!/bin/bash

function palin {
	z=$1
	r=0
	until [[ $z -eq 0 ]]; do
		b=`expr $z % 10`
		r=`expr $r \* 10 + $b`
		z=`expr $z / 10`
	done
	if [[ $r -eq $1 ]]; then
		echo "$1 is palindrome"
	else
		echo "$1 is not a palindrome"
	fi
}

if [[ -z "$1" ]]; then
	printf "Enter the goddamn number: "
	read n
	palin $n
else
	palin $1
fi