#!/bin/bash

function roots {
	d=$(($2*$2-4*$1*$3));
	r=0;
	if [[ $d -gt 0 ]]; then
		r=2;
	elif [[ $d -lt 0 ]]; then
		r=1;
	fi
	case $r in
		"0" )
			e=$(echo "scale=2;sqrt($d)/$1" | bc);
			x=$(echo "scale=2;0.5*(-($b)+($e))/$1" | bc);
			echo "Equal roots: $x";
			;;
		"1" )
			e=$(echo "scale=2;sqrt(-($d))/$1" | bc);
			b=$(echo "scale=2;0.5*(-($b))/$1" | bc);
			x=$(echo "scale=2;0.5*($e)/$1" | bc);
			echo "Imaginary roots: $b + $x i, $b - $x i";
			;;
		"2" )
			e=$(echo "scale=2;sqrt(($d))/$1" | bc);
			x1=$(echo "scale=2;0.5*(-($b)+($e))/$1" | bc);
			x2=$(echo "scale=2;0.5*(-($b)-($e))/$1" | bc);
			echo "Distinct roots: $x1, $x2";
			;;
	esac
}

if [[ -z "$1" || -z "$2" || -z "$3" ]]; then
	echo "Enter the god damn coeffecients: ";
	read a;
	read b;
	read c;
	roots $a $b $c;
else
	roots $1 $2 $3;
fi