#!/bin/bash

function gcd {
	a=$1;
	b=$2;
	if [[ $1 -le $2 ]]; then
		a=$2;
		b=$1;
	fi
	while [[ $b -gt 0 ]]; do
		t=$b;
		b=$(($a%$b));
		a=$t;
	done
	echo "GCD ($1, $2) = $a";
}

if [[ $1 -gt 0 && $2 -gt 0 ]]; then
	gcd $1 $2;
else
	a=0;
	b=0;
	while [[ $a -le 0 || $b -le 0 ]]; do
		echo "Enter two NON-NEGATIVE numbers.";
		read a;
		read b;
	done
	gcd $a $b;
fi